import AVFoundation
import ChessCore
import Foundation

/// The board's move and capture sounds.
///
/// A learner stepping through a game has no other signal that something
/// happened on a square they were not looking at; the two sounds are how the
/// move announces itself. They are deliberately distinct - a capture is the
/// scrape of the taken piece plus a knock, a quiet move is only the knock -
/// so the difference is audible without being looked at.
///
/// Assets are generated by `scripts/generate-sounds.py`.
@MainActor
final class BoardSounds {
    enum Kind: String {
        case move
        case capture
    }

    static let shared = BoardSounds()

    /// Mirrors the user's setting. Held here rather than checked at every
    /// call site so a board never has to know where the preference lives.
    ///
    /// Starts off and stays off until `GameLibrary` has read the stored
    /// preference. Nothing should make a sound before the app knows whether
    /// the user wants sound, and it also means no audio device is ever
    /// opened by code that merely replays a line without a UI - which is
    /// exactly what the unit tests do.
    var isEnabled = false

    /// One player per sound, reused. `AVAudioPlayer` can restart from zero
    /// mid-playback, which `NSSound` cannot do cleanly, and stepping quickly
    /// through a game retriggers well inside a sound's own length.
    private var players: [Kind: AVAudioPlayer] = [:]

    private init() {}

    func play(_ kind: Kind) {
        guard isEnabled, let player = player(for: kind) else { return }
        player.currentTime = 0
        player.play()
    }

    /// Plays the sound a replayed move calls for. Sound is a side effect of
    /// showing a move, never of deciding one, so this takes the already
    /// replayed board fact rather than re-deriving anything.
    func play(for move: ReplayedMove) {
        play(move.capturedPieceKind == nil ? .move : .capture)
    }

    private func player(for kind: Kind) -> AVAudioPlayer? {
        if let existing = players[kind] { return existing }
        guard let url = Bundle.main.url(forResource: kind.rawValue, withExtension: "wav"),
            let player = try? AVAudioPlayer(contentsOf: url)
        else {
            // A missing or unreadable asset must never be worse than
            // silence: the board keeps working, just without sound.
            return nil
        }
        player.prepareToPlay()
        players[kind] = player
        return player
    }
}
